### PR TITLE
new feauture

### PR DESCRIPTION
**Pull request by davttam**
Station project 1

### CODE REVIEW

**Comment by DavidGyulinyan** [comment]
All variables defined using the "var" keyword which is not desirable now when we have ES6 futures like "let" and "const".
All code written in one document, project is not so big but anyway it should be in different documents like style.css for styles, script.js for JavaScript. Last remark is about Regexp, there were no Regexp in the requirements

**Comment by davttam** [comment]
Thanks for your review David. I agree with you and'll take into account. I have a long-standing habit of writing var . About Regexp. I had no idea how to write without regexp. What can you offer in order to avoid it?

**Comment by DavidGyulinyan** [comment]
I'll suggest you to use ES6 methods split, filter etc.

**Comment by davttam** [comment]
Thank you, I'll try that way

**Pull request merged**
